services:
  bot:
    build:
      context: .
    container_name: "discord-bot"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    restart: "always"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ".env"
